### ISSUE TITLE
Not working on Android Browser 2.3

### ISSUE THREAD

**Issue by gabrielmaldi** [axemclion/IndexedDBShim#73]
Hey, thank you for this great project!

I have found that it doesn't work on Android's stock Browser (not Chrome) on android 2.3 (2.3.7 to be more specific).

I tracked the issue down to the implementation of StringList (util.js). The problem is that somehow the _items property doesn't retain its value, and when a call to any of StringList's methods occurs (the first one is contains), the script fails miserably when executing undefined.indexOf. I also found that outsiders can't call push or splice, those are always undefined.

The errors are the following:

``` js
var planets = new StringList();
planets.contains("Earth"); //Uncaught TypeError: Cannot call method 'indexOf' of undefined
planets.push("Mars"); //Uncaught TypeError: Property 'push' of object #<an Object> is not a function
```

FWIW, I reversed the changes made in this commit: https://github.com/axemclion/IndexedDBShim/commit/c17ebdbb48e6796c217a74aef4b38642e0b37240#src/util.js and that makes it work.

Here's a fiddle to repro: http://jsfiddle.net/fcFbB/5/show/

UPDATE:

The bugs repros on the actual device (LG Optimus Elite), not on the simulator (at least not using BrowserStack's 2.3 SII: http://bit.ly/1d3KkDU - there's an LG Optimus 3D with 2.2 but does not repro either).

Don't know if you need to get your hands on a device to actually fix this.

Thanks!

**Comment by Psithief** [comment]
Rolling back my additions fixes the problem? That makes it my problem :smile: 

I am currently guessing that the LG Optimus has a buggy implementation of `Object.defineProperty`.
Is the problem still present if you only comment out the following?

``` javascript
//Internal functions on the prototype have been made non-enumerable below.
if (Object.defineProperty)
    Object.defineProperty(this, '_items', {enumerable:false});
```

``` javascript
if (Object.defineProperty)
    for(var i in {'indexOf':false, 'push':false, 'splice':false})
        Object.defineProperty(StringList.prototype, i, {enumerable:false});
```

**Comment by gabrielmaldi** [comment]
You're good at guessing, haha; that does it!

I suppose there's not much we can do: remove those lines entirely (I understand they're just making StringList's public interface cleaner), or add a condition, which seems hard because there's no reliable way to know if Object.defineProperty will work properly... perhaps just a heads up in the documentation?

Thank you for coming back so fast.

**Comment by Psithief** [comment]
Hmm, I think there is a way to check whether it works by using the exact error the problem causes.

Something along the lines of:

``` javascript
var cleanInterface = false, testObject = {test: true}
//Test whether Object.defineProperty really works.
if (Object.defineProperty) {
  try {
    Object.defineProperty(testObject, 'test',{enumerable:false});
    if (testObject.test)
      cleanInterface = true
  } catch (e) {
    //Object.defineProperty does not work as intended.
  }
}
```

Then replacing the `if (Object.defineProperty)` lines with `if (cleanInterface)`.

I would be interested to hear if this snippet by itself works as intended on the LG Optimus Elite (leaving `cleanInterface = false` and catching the `TypeError`).

It would be good to know if the issue is present in all scopes. If true, I can submit another pull request with a more concise check.

**Comment by gabrielmaldi** [comment]
Yeah, that solution does it. Honestly, I don't know why I didn't see it, but I'm inclined to think that it was the 12 hours of non-stop work and lack of sleep at that point in the night, hahaha.

Here's the cross-browser working fiddle: http://jsfiddle.net/fcFbB/8/

What did you mean with "if the issue is present in all scopes"? Didn't get you.

Thanks!

**Comment by gabrielmaldi** [comment]
Fixed in #130

**Comment by Psithief** [comment]
@gabrielmaldi
This was almost a year ago but I was throwing out random guesses as to what might be wrong with the JavaScript engine of that phone. (i.e. some sort of bug where the object with the properties could see those added properties itself but other objects could not. Local vs. global scope.) I think it had more to do with what I had been reading and thinking about at the time rather than anything insightful.

However, as you reported the script worked with the suggested change, it was nothing of the sort!

I think the point has passed where the shame of leaving that question unanswered exceeded the embarrassment in explaining what I was thinking. :smile:

**Comment by gabrielmaldi** [comment]
:laughing: that's OK, we've all been there, no worries! I just happened to come across that PR and then saw that this issue was still open so I closed it.
